language: node_js
node_js:
- "6.4.0"

before_install:
    - which git
    - git --version

script:
    - npm test

env:
  global:
      - COMMIT_AUTHOR_EMAIL: "7884288+fogine@users.noreply.github.com"
